version: '3.6'

services:
  webhooks:
    build: "."
    volumes:
      - ./webhook:/etc/webhook
      - ./build:/target/
    tmpfs: /tmp/build
    ports:
      - 127.0.0.1:9001:9000
    command: "-verbose -hooks=/etc/webhook/hooks.json"
    restart: always

  liberation-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=liberation
    ports:
      - 33061:3306
    restart: always

